var express = require('express');
var router = express.Router();
var controller = require('../controllers/controller');
router.get('/getTweetData', controller.getTweetData);
router.get('/getTweetTrends', controller.getTweetTrends);
router.get('/getRetweetPerMinGraph', controller.getRetweetPerMinGraph);
router.get('/getRetweetGraph', controller.getRetweetGraph);
router.get('/getTweetGraph', controller.getTweetGraph);
router.get('/getBarCountGraph', controller.getBarCountGraph);
router.get('/getBarCountGraph2', controller.getBarCountGraph2);
router.get('/getWordClouds', controller.getWordClouds);
router.get('/getTopTrends', controller.getTopTrends);
router.get('/getAutoCompleteSearch', controller.getAutoCompleteSearch);
router.get('/getSearch/:keyword', controller.getSearchByKeyword);
router.get('/getGraphSearch/:keyword', controller.getGraphSearchByKeyword);
router.get('/getMoreTweet', controller.getMoreTweet);
router.post('/filterTweet', controller.filterTweet);
router.post('/filterTweetBySearch', controller.filterTweetBySearch);
router.get('/getCard', controller.getCard);
router.get('/getAnnotation', controller.getAnnotation);
module.exports = router;
